# Generated by Django 5.0.6 on 2024-06-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('client', 'Client'), ('agent', 'Agent')], default='manager', max_length=10),
        ),
    ]
